### ISSUE TITLE
Utils > gParted > 64 bit > (any DE) > no kernel parameters fails!

### ISSUE THREAD

**Issue by Synergyst** [IsaacSchemm/netbootcd#7]
The title explains the process in which to replicate the issue.
The 'tinycorelinux.net' website 404's and the NetBootCD menu fails to a CLI.

I think the problem is simply a typo in the URL that points to the 64-bit version of the tinycorelinux.net website.
I have tested the 32-bit version with success for my use case.

Kind regards.

**Comment by IsaacSchemm** [comment]
I pushed a couple commits to update the Core links to 8.x, fix the path, and another issue that cropped up (the 64-bit version doesn't have Xvesa, so I have to load the full-blown Xorg-7.7.) Both should work now, although since 32-bit has Xvesa it'll download faster.

Use the "download" link on an existing NetbootCD to get the new script - next time I make a new ISO this will be included.
